"""
Open Venture Framework (OVF)
============================
Documented startup financing and exit calculations; research extensions are planned.
"""

__version__ = "0.1.0-alpha"

from ovf import governance, opm, pme, presets, rounds
from ovf.antidilution import (
    BROAD_BASED_NVCA,
    BROAD_BASED_WITH_RESERVED_POOL,
    NARROW_BASED_OUTSTANDING_STOCK,
    CapitalizationBeforeIssue,
    ConversionPriceAdjustment,
    DeemedOutstanding,
    DeemedOutstandingDefinition,
    DilutiveIssuance,
    conversion_ratio,
    deemed_outstanding,
    full_ratchet,
    weighted_average,
)
from ovf.contracts.captable import CapTable, Payout
from ovf.contracts.safes import (
    MFNAmendment,
    MFNResolution,
    PostMoneyDiscountSAFE,
    PostMoneyMFNSAFE,
    SafeConversionResult,
    mfn_resolution,
    resolve_mfn,
    safe_post_discount,
    safe_post_mfn,
    solve_priced_round_with_safes,
)
from ovf.contracts.securities import (
    CommonStock,
    CumulativeDividend,
    DividendAccrual,
    DividendCapBasis,
    DividendDayCount,
    DividendSettlement,
    NonCumulativeDividend,
    PostMoneySAFE,
    PreferredExitTerms,
    PreferredStock,
    PreMoneySAFE,
    Security,
    StockOptionPool,
    common,
    cumulative_dividend,
    non_cumulative_dividend,
    option_pool,
    preferred,
    safe_post,
    safe_pre,
)
from ovf.core.types import (
    Money,
    Multiple,
    Percentage,
    Seniority,
    ShareCount,
    SharePrice,
)
from ovf.financing import (
    FULL_RATCHET,
    UNPROTECTED,
    AntiDilutionProtection,
    ExemptionDetermination,
    FinancingResult,
    NewIssue,
    PositionAdjustment,
    adjust_position,
    apply_dilutive_issuance,
    capitalization_before_issue,
    weighted_average_protection,
)
from ovf.governance import (
    ApprovalTally,
    CollectiveConversion,
    CollectiveConversionResult,
    GovernanceIndeterminateError,
    HolderDecision,
    VoteComparison,
    VoteRequirement,
    resolve_collective_conversion,
)
from ovf.instruments import (
    AccrualMethod,
    ConvertibleNote,
    DayCount,
    DebtAccrual,
    DebtClaim,
    DebtInstrument,
    NoteConversion,
    NoteExitTreatment,
    VentureDebt,
    convertible_note,
    debt,
    venture_debt,
)
from ovf.opm import (
    BreakpointSchedule,
    Discontinuity,
    DlomEstimate,
    OpmAssumptionError,
    OpmError,
    OpmInputs,
    OpmResult,
    breakpoint_schedule,
    dlom_comparison,
    opm_allocate,
)

# Straight from the submodule: `ovf.opm` deliberately leaves this name bound to the module
# of the same name, and no module competes for it here. See ovf/opm/__init__.py.
from ovf.opm.backsolve import backsolve
from ovf.rounds import (
    ExistingPreferred,
    NewSeries,
    PoolChange,
    PricedRound,
    RoundCapitalization,
    RoundResult,
    SafeConversion,
    SeniorityPlacement,
    apply_priced_round,
    explicit_seniority,
    pari_passu_with,
    pool_increase,
    pool_target_unallocated,
    round_capitalization,
)
from ovf.waterfall import (
    DebtSettlement,
    EquilibriumSurvey,
    WaterfallConvergenceError,
    WaterfallResult,
    accrue_dividends,
    enumerate_equilibria,
    multi_position_holders,
    settle_debt,
)

__all__ = [
    "WaterfallResult",
    "WaterfallConvergenceError",
    "EquilibriumSurvey",
    "enumerate_equilibria",
    "multi_position_holders",
    "__version__",
    # Core types
    "Money",
    "ShareCount",
    "SharePrice",
    "Percentage",
    "Multiple",
    "Seniority",
    # Securities
    "Security",
    "CommonStock",
    "PreferredStock",
    "PostMoneySAFE",
    "PreMoneySAFE",
    "StockOptionPool",
    "common",
    "preferred",
    "safe_post",
    "safe_pre",
    "option_pool",
    # CapTable & Safes
    "CapTable",
    "Payout",
    "SafeConversionResult",
    "solve_priced_round_with_safes",
    # Debt instruments (ovf.instruments)
    "DebtInstrument",
    "ConvertibleNote",
    "VentureDebt",
    "debt",
    "convertible_note",
    "venture_debt",
    "AccrualMethod",
    "DayCount",
    "NoteExitTreatment",
    "DebtAccrual",
    "DebtClaim",
    "NoteConversion",
    "DebtSettlement",
    "settle_debt",
    # Anti-dilution (ovf.antidilution)
    "weighted_average",
    "full_ratchet",
    "conversion_ratio",
    "deemed_outstanding",
    "CapitalizationBeforeIssue",
    "DeemedOutstandingDefinition",
    "DeemedOutstanding",
    "DilutiveIssuance",
    "ConversionPriceAdjustment",
    "BROAD_BASED_NVCA",
    "BROAD_BASED_WITH_RESERVED_POOL",
    "NARROW_BASED_OUTSTANDING_STOCK",
    # Fund performance: dated flows, certified IRR and public-market equivalents (ovf.pme)
    "pme",
    # NVCA model term-sheet presets (ovf.presets)
    "presets",
    # Financing rounds (ovf.rounds, ovf.contracts.safes)
    "rounds",
    "apply_priced_round",
    "PricedRound",
    "NewSeries",
    "ExistingPreferred",
    "RoundResult",
    "RoundCapitalization",
    "round_capitalization",
    "SafeConversion",
    "PoolChange",
    "pool_target_unallocated",
    "pool_increase",
    "SeniorityPlacement",
    "pari_passu_with",
    "explicit_seniority",
    "PostMoneyDiscountSAFE",
    "PostMoneyMFNSAFE",
    "safe_post_discount",
    "safe_post_mfn",
    "MFNResolution",
    "MFNAmendment",
    "mfn_resolution",
    "resolve_mfn",
    # Option Pricing Method (ovf.opm). The subpackage carries the rest, including the
    # four marketability discounts, which have no default and are not blended.
    "opm",
    "breakpoint_schedule",
    "BreakpointSchedule",
    "Discontinuity",
    "opm_allocate",
    "OpmInputs",
    "OpmResult",
    "backsolve",
    "dlom_comparison",
    "DlomEstimate",
    "OpmError",
    "OpmAssumptionError",
    # Governance (ovf.governance)
    "governance",
    "CollectiveConversion",
    "VoteRequirement",
    "VoteComparison",
    "resolve_collective_conversion",
    "CollectiveConversionResult",
    "HolderDecision",
    "ApprovalTally",
    "GovernanceIndeterminateError",
    # Dividends (ovf.contracts.securities, ovf.waterfall)
    "CumulativeDividend",
    "NonCumulativeDividend",
    "DividendAccrual",
    "PreferredExitTerms",
    "cumulative_dividend",
    "non_cumulative_dividend",
    "DividendDayCount",
    "DividendSettlement",
    "DividendCapBasis",
    "accrue_dividends",
    # Financing events (ovf.financing)
    "apply_dilutive_issuance",
    "adjust_position",
    "capitalization_before_issue",
    "AntiDilutionProtection",
    "weighted_average_protection",
    "FULL_RATCHET",
    "UNPROTECTED",
    "ExemptionDetermination",
    "NewIssue",
    "FinancingResult",
    "PositionAdjustment",
]
