"""PME-F1--F19: source/hand-derived fixtures; see docs/pme-fixtures.md.

Written before viewing/importing any production PME code. Expected values are
literal rationals/decimals, never generated by either implementation at import.
An empty reviewed_by means no external specialist has reviewed this fixture.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from decimal import Decimal
from fractions import Fraction as Q

from .pme_oracle import DayCount, Flow, InterimNavPolicy, Series

MICROSOFT_URL = "https://support.microsoft.com/en-us/excel/functions/xirr-function"
GGS_URL = (
    "https://allocatortraining.com/wp-content/uploads/2023/06/"
    "Benchmarking-PE-Direct-Alpha-Method.pdf"
)
Y0, Y1, Y2 = date(2021, 1, 1), date(2022, 1, 1), date(2023, 1, 1)
CONSTANT = ((Y0, Q(100)), (Y1, Q(100)), (Y2, Q(100)))
GROWING = ((Y0, Q(100)), (Y1, Q(110)), (Y2, Q(121)))


def series(*rows: tuple[str | date, int | str | Q]) -> Series:
    return tuple((date.fromisoformat(d) if isinstance(d, str) else d, Q(a)) for d, a in rows)


@dataclass(frozen=True)
class PmeFixture:
    case_id: str
    description: str
    amounts: Series
    as_of: date
    nav: tuple[date, Q] | None
    day_count: DayCount
    expected: dict[str, object]
    derivation: str
    levels: Series = ()
    stale_nav: str = "refuse"
    source_url: str = "docs/pme-contract.md"
    reviewed_by: str = ""

    @property
    def flows(self) -> tuple[Flow, ...]:
        return tuple(
            Flow(d, "contribution" if a < 0 else "distribution", abs(a)) for d, a in self.amounts
        )


PME_FIXTURES = (
    PmeFixture(
        "PME-F1",
        "Microsoft published XIRR example",
        series(
            ("2008-01-01", -10000),
            ("2008-03-01", 2750),
            ("2008-10-30", 4250),
            ("2009-02-15", 3250),
            ("2009-04-01", 2750),
        ),
        date(2009, 4, 1),
        (date(2009, 4, 1), Q(0)),
        "ACT/365F",
        {
            "irr": Decimal("0.3733625335188315103084554119145548241713"),
            "published_irr": Decimal("0.373362535"),
            "status": "unique",
            "complete": True,
        },
        "Solve -10000+2750*q^(-60/365)+4250*q^(-303/365)"
        "+3250*q^(-411/365)+2750*q^(-456/365)=0, q=1+r.",
        source_url=MICROSOFT_URL,
    ),
    *(
        PmeFixture(
            f"PME-F2{suffix}",
            "Two-flow closed form spanning Feb 29",
            series(("2019-07-01", -100), ("2020-07-01", 121)),
            date(2020, 7, 1),
            (date(2020, 7, 1), Q(0)),
            convention,
            {"irr": Decimal(expected), "year_fraction": t, "status": "unique", "complete": True},
            "r=(121/100)^(1/t)-1; ISDA t=184/365+182/366.",
        )
        for suffix, convention, t, expected in (
            ("a", "ACT/365F", Q(366, 365), "0.2093699710881278525772505269803884236053"),
            ("b", "ACT/365.25", Q(488, 487), "0.2095274475550495656185518306727665038204"),
            ("c", "ACT/ACT-ISDA", Q(66887, 66795), "0.2096827922187858707054071472140171420283"),
        )
    ),
    PmeFixture(
        "PME-F3",
        "Two crossing roots, neither selected",
        series((Y0, -100), (Y1, 230), (Y2, -132)),
        Y2,
        (Y2, Q(0)),
        "ACT/365F",
        {
            "roots": (Decimal("0.1"), Decimal("0.2")),
            "irr": None,
            "status": "multiple",
            "complete": True,
        },
        "-100*q^2+230*q-132=-100*(q-1.1)*(q-1.2).",
    ),
    PmeFixture(
        "PME-F4",
        "Proven no real root",
        series((Y0, -100), (Y1, 100), (Y2, -100)),
        Y2,
        (Y2, Q(0)),
        "ACT/365F",
        {"roots": (), "irr": None, "status": "none", "complete": True},
        "-100*(q^2-q+1)=-100*((q-1/2)^2+3/4)<0 for all q>0.",
    ),
    PmeFixture(
        "PME-F5",
        "Tangent root remains undetermined by contract",
        series((Y0, -100), (Y1, 200), (Y2, -100)),
        Y2,
        (Y2, Q(0)),
        "ACT/365F",
        {"roots": (Decimal(0),), "irr": None, "status": "undetermined", "complete": False},
        "-100*(q-1)^2=0 has a double root q=1; report tangent, never a selected IRR.",
    ),
    PmeFixture(
        "PME-F6",
        "Constant benchmark identities",
        series((Y0, -100), (Y1, 30)),
        Y2,
        (Y2, Q(90)),
        "ACT/365F",
        {
            "tvpi": Q(6, 5),
            "ks": Q(6, 5),
            "scale": Q(1, 3),
            "ln_terminal": Q(70),
            "irr": Decimal("0.1104686356149273029732326511932719896781"),
            "alpha": Decimal("0.1104686356149273029732326511932719896781"),
            "status": "unique",
            "complete": True,
        },
        "TVPI=KS=(30+90)/100; s=(100-90)/30; q=(3+sqrt(369))/20.",
        levels=CONSTANT,
    ),
    PmeFixture(
        "PME-F7",
        "Fund exactly replicates the index",
        series((Y0, -100), (Y1, 55)),
        Y2,
        (Y2, Q(121, 2)),
        "ACT/365F",
        {
            "ks": Q(1),
            "alpha": Decimal(0),
            "scale": Q(1),
            "ln_terminal": Q(121, 2),
            "irr": Decimal("0.1"),
            "status": "unique",
            "complete": True,
        },
        "FV(C)=121; FV(D)=55*121/110=121/2; NAV=121/2.",
        levels=GROWING,
    ),
    PmeFixture(
        "PME-F8",
        "Realised fund KS equals reciprocal scale",
        series((Y0, -100), (Y1, 60), (Y2, 72)),
        Y2,
        (Y2, Q(0)),
        "ACT/365F",
        {
            "ks": Q(138, 121),
            "scale": Q(121, 138),
            "ln_terminal": Q(-17),
            "irr": Decimal("0.2"),
            "alpha": Q(1, 11),
            "status": "unique",
            "complete": True,
        },
        "FV(C)=121; FV(D)=60*121/110+72=138; NAV=0.",
        levels=GROWING,
    ),
    PmeFixture(
        "PME-F9",
        "ICM short path and multiple ICM roots",
        series((Y0, -100), (Y1, 150)),
        Y2,
        (Y2, Q(10)),
        "ACT/365F",
        {
            "ks": Q(175, 121),
            "scale": Q(37, 55),
            "ln_terminal": Q(-44),
            "positions": series((Y0, 100), (Y1, -40), (Y2, -44)),
            "first_short_date": Y1,
            "went_short": True,
            "minimum_position": Q(-44),
            "icm_roots": (Decimal("-0.6"), Decimal("0.1")),
            "icm_status": "multiple",
            "icm_complete": True,
            "icm_irr": None,
            "irr": Decimal("0.5639410298049853193676507954991916577004"),
            "status": "unique",
            "complete": True,
        },
        "V:100 -> 100*1.1-150=-40 -> -44; -100*q^2+150*q-44=-100*(q-.4)*(q-1.1).",
        levels=GROWING,
    ),
    PmeFixture(
        "PME-F10a",
        "Stale end-of-day NAV cash roll-forward",
        series((Y0, -100), (Y1, 10), ("2022-06-01", -20), (Y2, 15)),
        Y2,
        (Y1, Q(80)),
        "ACT/365F",
        {
            "residual": Q(85),
            "contributions_after": Q(20),
            "distributions_after": Q(15),
            "tvpi": Q(11, 12),
            "dpi": Q(5, 24),
            "rvpi": Q(17, 24),
        },
        "80+20-15=85; same-day distribution 10 already reflected in reported NAV;"
        " TVPI=(25+85)/120=11/12.",
        stale_nav="roll_forward_cash_adjusted",
    ),
    PmeFixture(
        "PME-F10b",
        "Inconsistent stale NAV refused",
        series((Y0, -100), (Y1, 10), ("2022-06-01", -20), (Y2, 115)),
        Y2,
        (Y1, Q(80)),
        "ACT/365F",
        {"refused": True},
        "80+20-115=-15 is impossible under the zero-return roll-forward assumption.",
        stale_nav="roll_forward_cash_adjusted",
    ),
    PmeFixture(
        "PME-F11",
        "Gross multiples survive same-date netting",
        series((Y0, -100), (Y0, 20), (Y1, -10), (Y1, 10), (Y2, 88)),
        Y2,
        (Y2, Q(0)),
        "ACT/365F",
        {
            "net_by_date": series((Y0, -80), (Y2, 88)),
            "netted_to_zero": (Y1,),
            "tvpi": Q(59, 55),
            "ks": Q(59, 55),
            "scale": Q(55, 59),
            "ln_terminal": Q(-8),
            "irr": Decimal("0.0488088481701515469914535136799375984753"),
            "status": "unique",
            "complete": True,
        },
        "Gross C=110, D=118; net=(-80,0,88); r=sqrt(88/80)-1.",
        levels=CONSTANT,
    ),
    PmeFixture(
        "PME-F12",
        "Gredil-Griffiths-Stucke 2014 Exhibits 5-6 displayed inputs",
        series(
            ("2001-12-31", -100),
            ("2003-12-31", -100),
            ("2003-12-31", 25),
            ("2005-12-31", -50),
            ("2005-12-31", 150),
            ("2007-12-31", 150),
            ("2009-12-31", 100),
        ),
        date(2010, 12, 31),
        (date(2010, 12, 31), Q(75)),
        "ACT/365F",
        {
            "tvpi": Q(2),
            "ks": Q(1990055721, 1193950768),
            "scale": Q(912343468, 1708448421),
            "ln_terminal": Q(-514497653, 3754764),
            "alpha": Decimal("0.1256031689842718129140562878513095672908"),
            "irr": Decimal("0.1752012983239102762880181532804552349698"),
            "status": "unique",
            "complete": True,
            "published_ks": Decimal("1.67"),
            "published_alpha": Decimal("0.126"),
            "published_irr": Decimal("0.175"),
            "went_short": True,
            "first_short_date": date(2007, 12, 31),
            "minimum_position": Q(-514497653, 3754764),
            "icm_roots": (
                Decimal("-0.2725508866987863647654264584613866681767"),
                Decimal("0.0596701431386367255176898473485018680819"),
            ),
            "icm_status": "multiple",
            "icm_complete": True,
            "icm_irr": None,
        },
        "Use displayed integer index levels exactly; source future values are rounded"
        " and reveal undisplayed index precision (100*131/100 is printed as 130).",
        levels=series(
            *(
                (date(2001 + i, 12, 31), v)
                for i, v in enumerate((100, 78, 100, 111, 117, 135, 142, 90, 113, 131))
            )
        ),
        source_url=GGS_URL,
    ),
)

BY_ID = {fixture.case_id: fixture for fixture in PME_FIXTURES}


@dataclass(frozen=True)
class MpmeFixture(PmeFixture):
    nav_history: Series = ()
    interim_nav: InterimNavPolicy = "refuse"
    max_nav_gap_days: int = 0


Y3 = date(2024, 1, 1)
TEN_PERCENT = (*GROWING, (Y3, Q(1331, 10)))
JAN6, JAN11 = date(2021, 1, 6), date(2021, 1, 11)

MPME_FIXTURES = (
    MpmeFixture(
        "PME-F13",
        "Three distributions, same-day call invested before proportional sale",
        series((Y0, -100), (Y1, -40), (Y1, 80), (Y2, 50), (Y3, 120)),
        Y3,
        (Y3, Q(60)),
        "ACT/365F",
        {
            "before": (Q(100), Q(160), Q(100), Q(90)),
            "weights": (Q(0), Q(1, 2), Q(1, 4), Q(2, 3)),
            "sales": (Q(0), Q(80), Q(25), Q(60)),
            "after": (Q(100), Q(80), Q(75), Q(30)),
            "fund_navs": (None, Q(80), Q(150), Q(60)),
            "sources": ("none", "reported", "reported", "reported"),
            "observation_dates": (None, Y1, Y2, Y3),
            "mpme_series": series((Y0, -100), (Y1, 40), (Y2, 25), (Y3, 90)),
            "mpme_irr": Decimal("0.2151953740642772566525964996136581841420"),
            "fund_irr": Decimal("0.5146759923822105766006955715018281837973"),
            "max_nav_gap_used_days": 0,
        },
        "X:100,100*120/100+40=160,80*150/120=100,75*180/150=90;"
        " w:0,80/160,50/200,120/180; sales:0,80,25,60; NAV:100,80,75,30.",
        levels=series((Y0, 100), (Y1, 120), (Y2, 150), (Y3, 180)),
        nav_history=series((Y1, 80), (Y2, 150), (Y3, 60)),
    ),
    MpmeFixture(
        "PME-F14",
        "Tracking-fund identity at all three distributions and the terminal NAV",
        series((Y0, -100), (Y1, -10), (Y1, 60), (Y2, 22), (Y3, Q(121, 5))),
        Y3,
        (Y3, Q(121, 5)),
        "ACT/365F",
        {
            "before": (Q(100), Q(120), Q(66), Q(242, 5)),
            "weights": (Q(0), Q(1, 2), Q(1, 3), Q(1, 2)),
            "sales": (Q(0), Q(60), Q(22), Q(121, 5)),
            "after": (Q(100), Q(60), Q(44), Q(121, 5)),
            "fund_navs": (None, Q(60), Q(44), Q(121, 5)),
            "sources": ("none", "reported", "reported", "reported"),
            "observation_dates": (None, Y1, Y2, Y3),
            "mpme_series": series((Y0, -100), (Y1, 50), (Y2, 22), (Y3, Q(242, 5))),
            "mpme_irr": Q(1, 10),
            "fund_irr": Q(1, 10),
            "spread": Q(0),
            "log_spread": Q(0),
            "max_nav_gap_used_days": 0,
            "tracking": True,
        },
        "NAV:100 -> 110+10-60=60 -> 66-22=44 -> 48.4-24.2=24.2;"
        " X=D+NAV at every sale, so mPME distributions equal D and both IRRs are 1/10.",
        levels=TEN_PERCENT,
        nav_history=series((Y1, 60), (Y2, 44), (Y3, Q(121, 5))),
    ),
    MpmeFixture(
        "PME-F15",
        "Zero interim NAV liquidates the public position exactly",
        series((Y0, -100), (Y1, 150)),
        Y2,
        (Y2, Q(0)),
        "ACT/365F",
        {
            "before": (Q(100), Q(110), Q(0)),
            "weights": (Q(0), Q(1), Q(0)),
            "sales": (Q(0), Q(110), Q(0)),
            "after": (Q(100), Q(0), Q(0)),
            "fund_navs": (None, Q(0), None),
            "sources": ("none", "reported", "none"),
            "observation_dates": (None, Y1, None),
            "mpme_series": series((Y0, -100), (Y1, 110)),
            "mpme_irr": Q(1, 10),
            "fund_irr": Q(1, 2),
            "spread": Q(2, 5),
            "max_nav_gap_used_days": 0,
        },
        "X1=100*110/100=110; w1=150/(150+0)=1; sale=110; retained=(0/150)*110=0.",
        levels=GROWING,
        nav_history=series((Y1, 0), (Y2, 0)),
    ),
    *(
        MpmeFixture(
            f"PME-F16{suffix}",
            description,
            series((Y0, -100), (Y0, 10), (JAN6, -20), (JAN11, 30)),
            Y1,
            (Y1, Q(80)),
            "ACT/365F",
            expected,
            "End-of-day NAV0=90 already reflects D0=10; at Jan 11 NAV=90+20-30=80."
            " The observation is ten calendar days old; nine days is insufficient.",
            levels=series((Y0, 100), (JAN6, 100), (JAN11, 100), (Y1, 100)),
            nav_history=series((Y0, mark), (Y1, 80)),
            interim_nav=policy,
            max_nav_gap_days=gap,
        )
        for suffix, description, gap, policy, mark, expected in (
            (
                "a",
                "Cash-adjusted interim NAV at the inclusive gap limit",
                10,
                "roll_forward_cash_adjusted",
                90,
                {
                    "before": (Q(100), Q(110), Q(110), Q(80)),
                    "weights": (Q(1, 10), Q(0), Q(3, 11), Q(0)),
                    "sales": (Q(10), Q(0), Q(30), Q(0)),
                    "after": (Q(90), Q(110), Q(80), Q(80)),
                    "fund_navs": (Q(90), None, Q(80), None),
                    "sources": ("reported", "none", "rolled_forward", "none"),
                    "observation_dates": (Y0, None, Y0, None),
                    "mpme_series": series((Y0, -90), (JAN6, -20), (JAN11, 30), (Y1, 80)),
                    "mpme_irr": Q(0),
                    "fund_irr": Q(0),
                    "spread": Q(0),
                    "log_spread": Q(0),
                    "max_nav_gap_used_days": 10,
                    "tracking": True,
                },
            ),
            (
                "b",
                "Interim NAV beyond maximum gap is refused",
                9,
                "roll_forward_cash_adjusted",
                90,
                {"refused": "gap exceeds", "refused_date": JAN11},
            ),
            (
                "c",
                "Missing exact interim NAV under refuse policy",
                0,
                "refuse",
                90,
                {"refused": "missing interim NAV", "refused_date": JAN11},
            ),
            (
                "d",
                "Negative cash-adjusted interim NAV is refused",
                10,
                "roll_forward_cash_adjusted",
                1,
                {"refused": "negative rolled interim NAV", "refused_date": JAN11},
            ),
        )
    ),
    MpmeFixture(
        "PME-F17",
        "Same inputs make Long-Nickels short but mPME stays nonnegative",
        series((Y0, -100), (Y1, 150)),
        Y2,
        (Y2, Q(10)),
        "ACT/365F",
        {
            "before": (Q(100), Q(110), Q(121, 16)),
            "weights": (Q(0), Q(15, 16), Q(0)),
            "sales": (Q(0), Q(825, 8), Q(0)),
            "after": (Q(100), Q(55, 8), Q(121, 16)),
            "fund_navs": (None, Q(10), None),
            "sources": ("none", "reported", "none"),
            "observation_dates": (None, Y1, None),
            "mpme_series": series((Y0, -100), (Y1, Q(825, 8)), (Y2, Q(121, 16))),
            "mpme_irr": Q(1, 10),
            "fund_irr": Decimal("0.5639410298049853193676507954991916577004"),
            "max_nav_gap_used_days": 0,
            "ln_positions": series((Y0, 100), (Y1, -40), (Y2, -44)),
        },
        "w1=150/160=15/16; sale=110*15/16=825/8; NAV1=110/16=55/8;"
        " NAV2=(55/8)*121/110=121/16; ICM instead subtracts 150 and becomes -40, then -44.",
        levels=GROWING,
        nav_history=series((Y1, 10), (Y2, 10)),
    ),
    MpmeFixture(
        "PME-F18",
        "A distribution after full public liquidation has an exact zero sale",
        series((Y0, -20), (Y1, 1), (Y2, 1)),
        Y3,
        (Y3, Q(0)),
        "ACT/365F",
        {
            "before": (Q(20), Q(20), Q(0), Q(0)),
            "weights": (Q(0), Q(1), Q(1), Q(0)),
            "sales": (Q(0), Q(20), Q(0), Q(0)),
            "after": (Q(20), Q(0), Q(0), Q(0)),
            "fund_navs": (None, Q(0), Q(0), None),
            "sources": ("none", "reported", "reported", "none"),
            "observation_dates": (None, Y1, Y2, None),
            "mpme_series": series((Y0, -20), (Y1, 20)),
            "mpme_irr": Q(0),
            "fund_irr": Q(-3, 4),
            "spread": Q(-3, 4),
            "max_nav_gap_used_days": 0,
        },
        "First sale: X=20,w=1,sale=20,NAV=0; second sale: X=0,w=1,sale=0,NAV=0."
        " mPME IRR=0; fund polynomial 20*q^2-q-1 has positive root q=1/4.",
        levels=series((Y0, 100), (Y1, 100), (Y2, 100), (Y3, 100)),
        nav_history=series((Y1, 0), (Y2, 0)),
    ),
    *(
        MpmeFixture(
            f"PME-F19{suffix}",
            "A terminal distribution uses resolved NAV when history omits that date",
            series((Y0, -100), (Y1, 30)),
            Y1,
            nav,
            "ACT/365F",
            {
                "before": (Q(100), Q(110)),
                "weights": (Q(0), Q(3, 10)),
                "sales": (Q(0), Q(33)),
                "after": (Q(100), Q(77)),
                "fund_navs": (None, Q(70)),
                "sources": ("none", source),
                "observation_dates": (None, observed),
                "mpme_series": series((Y0, -100), (Y1, 110)),
                "mpme_irr": Q(1, 10),
                "fund_irr": Q(0),
                "spread": Q(-1, 10),
                "max_nav_gap_used_days": 0,
            },
            "NAV_T=70 (reported or resolved as 100-30); X=110,w=30/(30+70)=3/10;"
            " sale=33,NAV_mPME=77; terminal mPME net=110; interim gap limit is irrelevant.",
            levels=series((Y0, 100), (Y1, 110)),
            nav_history=series((Y0, 100)),
            stale_nav=stale,
        )
        for suffix, nav, stale, source, observed in (
            ("a", (Y1, Q(70)), "refuse", "reported", Y1),
            ("b", (Y0, Q(100)), "roll_forward_cash_adjusted", "rolled_forward", Y0),
        )
    ),
)

MPME_BY_ID = {fixture.case_id: fixture for fixture in MPME_FIXTURES}
