"""Write an ovf ``CapTable`` as an OCF v1.2.0 package.

The writer emits what ovf knows and what OCF v1.2.0 requires. Where OCF requires a field
ovf has no value for (stakeholder type, votes per share, authorized shares, issue dates),
it writes a stated placeholder and a ``comments`` entry on the object that carries it, so
anyone reading the package can tell data from filler. Payout-relevant values are written
exactly or not at all.

Refused, each with an error naming the security and the gap:

* participating preferred with no cap. OCF v1.2.0 has no participating flag; an absent
  ``participation_cap_multiple`` reads as non-participating, and any cap would invent a
  term, so this structure cannot be expressed in the format;
* term debt and venture debt. OCF v1.2.0 has no object for non-convertible debt;
* convertible notes outside what the reader accepts: compound or PIK accrual (OCF has no
  compounding frequency), a day count other than Actual/365 Fixed, or a stated exit
  treatment (OCF has no repayment trigger and does not define ``exit_multiple``);
* SAFEs and every other instrument this adapter has no OCF mapping for;
* option pools with allocated options (ovf holds no grant, strike or vesting data);
* a number that needs more than the 10 decimal places OCF ``Numeric`` allows.

Seniority is written inverted, because OCF repays a higher number first: with ``k``
distinct ovf preferred seniorities, the most senior becomes OCF ``k + 1``, the most junior
``2``, and the common class ``1``. Note seniority is NOT inverted: OCF's convertible scale
has "1 being highest seniority", so the most senior ovf debt rank becomes OCF ``1``.

A note's maturity date and qualified-financing threshold have no OCF field. They are
written into comments and trigger text only, and must be supplied again as ``note_terms``
(``ovf.ocf.note_terms_from``) to read the package back.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import json
import math
import os
import re
from collections.abc import Mapping
from decimal import ROUND_HALF_EVEN, Decimal, localcontext
from fractions import Fraction
from pathlib import Path
from typing import get_args

from ovf.contracts.captable import CapTable
from ovf.contracts.securities import CommonStock, PreferredStock, StockOptionPool
from ovf.instruments.debt import AccrualMethod, ConvertibleNote, DayCount, DebtInstrument
from ovf.ocf.notes import OCF_ISSUE_423
from ovf.ocf.schema import (
    NUMERIC_MAX_DECIMALS,
    OCF_VERSION,
    ConversionRight,
    ConversionTrigger,
    ConvertibleIssuance,
    FileReference,
    InterestRate,
    Issuer,
    Manifest,
    Monetary,
    Name,
    NoteConversionMechanism,
    OcfPackage,
    OcfUnsupportedError,
    ParticipationCapBasis,
    Ratio,
    RatioConversionMechanism,
    Stakeholder,
    StockClass,
    StockClassConversionRight,
    StockIssuance,
    StockPlan,
)
from ovf.waterfall import validate_securities

COMMON_CLASS_ID = "ovf-common"
_GENERATED = "Generated by ovf.to_ocf."
_CLASS_NOTE = (
    f"{_GENERATED} votes_per_share is a placeholder (ovf does not model voting); "
    "initial_shares_authorized is the number of shares issued in this class in the exported "
    "snapshot, not an authorized figure."
)
_STAKEHOLDER_NOTE = (
    f"{_GENERATED} name and stakeholder_type are placeholders; ovf records only a holder_id."
)
_ISSUANCE_NOTE = (
    f"{_GENERATED} date is the package as_of date and custom_id is the ovf security_id; "
    "ovf does not record issue dates or certificate numbers."
)
_UNKNOWN_BASIS_NOTE = "share_price 0 is ovf's 'cost basis unknown', not a recorded purchase price."
_PLAN_NOTE = f"{_GENERATED} Unallocated reserve only; ovf holds no grants for this plan."


def _numeric(value: float, where: str) -> str:
    """Exact fixed-point text for a float, or refuse when OCF Numeric cannot hold it."""
    if not math.isfinite(value):
        raise OcfUnsupportedError(f"{where} is not finite")
    text = format(Decimal(repr(value)), "f")
    decimals = len(text.partition(".")[2])
    if decimals > NUMERIC_MAX_DECIMALS:
        raise OcfUnsupportedError(
            f"{where} = {value!r} needs {decimals} decimal places; OCF Numeric allows at most "
            f"{NUMERIC_MAX_DECIMALS}, and ovf does not round a payout-relevant value on export."
        )
    return text


def _ratio(value: float) -> Ratio:
    """The shortest decimal that round-trips the float, as an exact integer fraction."""
    fraction = Fraction(Decimal(repr(value)))
    return Ratio(numerator=str(fraction.numerator), denominator=str(fraction.denominator))


def _conversion_price(price: str, ratio: Ratio) -> str:
    """Original Issue Price / ratio (NVCA: conversion shares = OIP / Conversion Price).

    Informational only; the reader uses ``ratio``. Rounded half-even to 10 decimals when
    the quotient does not terminate.
    """
    value = Fraction(Decimal(price)) / (
        Fraction(Decimal(ratio.numerator)) / Fraction(Decimal(ratio.denominator))
    )
    with localcontext() as context:
        context.prec = 80
        quotient = (Decimal(value.numerator) / Decimal(value.denominator)).quantize(
            Decimal(1).scaleb(-NUMERIC_MAX_DECIMALS), rounding=ROUND_HALF_EVEN
        )
    return format(quotient.normalize(), "f")


def _decimal_sum(texts: list[str]) -> str:
    return format(sum((Decimal(t) for t in texts), Decimal(0)), "f")


def _check_note(note: ConvertibleNote, as_of: dt.date) -> None:
    """Refuse a note the reader could not read back to the same terms."""
    where = f"ConvertibleNote {note.security_id!r}"
    if note.exit_treatment is not None:
        raise OcfUnsupportedError(
            f"{where} has exit_treatment {note.exit_treatment.value!r}. OCF v1.2.0 has no "
            "repayment trigger, and its exit_multiple does not say what it multiplies, so a "
            "stated exit treatment cannot be written. Export the unresolved note and call "
            "resolved() after reading it back."
        )
    if note.accrual is not AccrualMethod.SIMPLE:
        raise OcfUnsupportedError(
            f"{where} accrues {note.accrual.value} interest. OCF v1.2.0 has a compounding type "
            "but no compounding frequency (OCF issue #423 works an example of daily accrual "
            "with annual compounding), so compound and PIK notes are not expressible."
        )
    if note.day_count is not DayCount.ACT_365_FIXED:
        raise OcfUnsupportedError(
            f"{where} uses day count {note.day_count.value}. OCF v1.2.0 offers only ACTUAL_365 "
            "and 30_360; Actual/360 has no OCF value."
        )
    if note.issue_date > as_of:
        raise OcfUnsupportedError(
            f"{where} is issued on {note.issue_date}, after as_of {as_of}; the package would "
            "not describe the state it claims."
        )


def _note_issuance(note: ConvertibleNote, currency: str, seniority: int) -> ConvertibleIssuance:
    """One NOTE issuance with a single qualified-financing trigger and simple daily interest."""
    where = f"ConvertibleNote {note.security_id!r}"
    assert note.maturity_date is not None  # required by ConvertibleNote
    threshold = _numeric(
        note.qualified_financing_threshold, f"{where}.qualified_financing_threshold"
    )
    mechanism = NoteConversionMechanism(
        type="CONVERTIBLE_NOTE_CONVERSION",
        interest_rates=(
            InterestRate(
                rate=_numeric(note.annual_rate, f"{where}.annual_rate"),
                accrual_start_date=note.issue_date,
            ),
        ),
        day_count_convention="ACTUAL_365",
        interest_payout="DEFERRED",
        interest_accrual_period="DAILY",
        compounding_type="SIMPLE",
        conversion_discount=(
            _numeric(note.discount_rate, f"{where}.discount_rate") if note.discount_rate else None
        ),
        conversion_valuation_cap=(
            None
            if note.valuation_cap is None
            else Monetary(
                amount=_numeric(note.valuation_cap, f"{where}.valuation_cap"), currency=currency
            )
        ),
    )
    trigger = ConversionTrigger(
        type="AUTOMATIC_ON_CONDITION",
        trigger_id=f"{note.security_id}.qualified-financing",
        nickname="Qualified financing",
        trigger_condition=(
            f"Converts automatically in a financing raising at least {threshold} {currency} "
            "of new money. Written by ovf.to_ocf from qualified_financing_threshold; OCF "
            "v1.2.0 has no structured field for it, and ovf never parses this text."
        ),
        conversion_right=ConversionRight(
            type="CONVERTIBLE_CONVERSION_RIGHT",
            conversion_mechanism=mechanism.model_dump(mode="json", exclude_none=True),
            converts_to_future_round=True,
        ),
    )
    return ConvertibleIssuance(
        object_type="TX_CONVERTIBLE_ISSUANCE",
        id=f"ovf-issuance-{note.security_id}",
        date=note.issue_date,
        security_id=note.security_id,
        custom_id=note.security_id,
        stakeholder_id=note.holder_id,
        security_law_exemptions=(),
        investment_amount=Monetary(
            amount=_numeric(note.principal, f"{where}.principal"), currency=currency
        ),
        convertible_type="NOTE",
        conversion_triggers=(trigger,),
        seniority=seniority,
        comments=(
            f"{_GENERATED} custom_id is the ovf security_id. OCF v1.2.0 has no field for a "
            f"note's maturity date or its qualified-financing threshold: maturity_date "
            f"{note.maturity_date.isoformat()} and qualified_financing_threshold {threshold} "
            f"{currency} appear only in these comments and in trigger_condition, which ovf "
            "never parses. The day count is Actual/365 Fixed, written as ACTUAL_365, whose "
            f"meaning OCF leaves open ({OCF_ISSUE_423}). Supply all three again as note_terms "
            "(ovf.ocf.note_terms_from) when reading this package.",
        ),
    )


def to_ocf(
    table: CapTable,
    *,
    issuer: Issuer,
    currency: str,
    as_of: dt.date,
    generated_at: dt.datetime | None = None,
    stakeholders: Mapping[str, Stakeholder] | None = None,
    participation_cap_basis: ParticipationCapBasis = "total",
) -> OcfPackage:
    """Express ``table`` as an in-memory OCF v1.2.0 package.

    ``issuer``, ``currency`` and ``as_of`` are required because OCF requires them and ovf
    does not hold them. ``generated_at`` defaults to midnight UTC on ``as_of`` so output is
    deterministic. ``stakeholders`` maps holder_id to a full Stakeholder record; holders
    without one get a placeholder that says so in its comments. Preferred positions with
    identical terms share one stock class; each position is one issuance.
    """
    if participation_cap_basis not in get_args(ParticipationCapBasis):
        raise ValueError(
            f"participation_cap_basis must be one of {get_args(ParticipationCapBasis)}"
        )
    if not re.fullmatch(r"[A-Z]{3}", currency):
        raise ValueError(f"currency must be an ISO 4217 code such as 'USD'; got {currency!r}")
    if generated_at is None:
        generated_at = dt.datetime.combine(as_of, dt.time(), tzinfo=dt.UTC)
    elif generated_at.tzinfo is None:
        raise ValueError("generated_at must be timezone-aware (OCF uses RFC 3339 date-time)")

    validate_securities(table.securities)
    equity: list[CommonStock | PreferredStock] = []
    pools: list[StockOptionPool] = []
    notes: list[ConvertibleNote] = []
    for security in table.securities:
        if isinstance(security, PreferredStock):
            if security.dividend is not None:
                raise OcfUnsupportedError(
                    f"PreferredStock {security.security_id!r} carries a dividend term. "
                    "OCF v1.2.0 StockClass has no dividend fields at all: no rate, accrual "
                    "method, day count, accrual start or conversion settlement. Writing the "
                    "class without them would silently drop an accruing claim and understate "
                    "the holder at exit, so the export is refused instead."
                )
            if security.participating and security.participation_cap is None:
                raise OcfUnsupportedError(
                    f"PreferredStock {security.security_id!r} is participating with no cap. "
                    "OCF v1.2.0 has no participating flag: an absent participation_cap_multiple "
                    "reads as non-participating, and writing any cap would invent a term. "
                    "Participating-uncapped preferred is not expressible in OCF v1.2.0."
                )
            equity.append(security)
        elif isinstance(security, CommonStock):
            equity.append(security)
        elif isinstance(security, StockOptionPool):
            if security.allocated_shares > 0:
                raise OcfUnsupportedError(
                    f"StockOptionPool {security.security_id!r} has allocated_shares "
                    f"{security.allocated_shares}; OCF grants need holders, strikes and "
                    "vesting terms that ovf does not hold."
                )
            pools.append(security)
        elif isinstance(security, ConvertibleNote):
            _check_note(security, as_of)
            notes.append(security)
        elif isinstance(security, DebtInstrument):
            raise OcfUnsupportedError(
                f"{type(security).__name__} {security.security_id!r} is non-convertible debt. "
                "OCF v1.2.0 has no object for a loan or a venture debt facility (its only "
                "debt-like issuance is TX_CONVERTIBLE_ISSUANCE), so a claim that ranks ahead "
                "of all equity cannot be written."
            )
        else:
            raise OcfUnsupportedError(
                f"{type(security).__name__} {security.security_id!r} has no OCF mapping in "
                "this adapter; convert SAFEs with solve_priced_round_with_safes before export."
            )

    preferred = [s for s in equity if isinstance(s, PreferredStock)]
    levels = sorted({p.seniority for p in preferred})
    ocf_seniority = {level: str(len(levels) - index + 1) for index, level in enumerate(levels)}

    class_of: dict[str, str] = {}
    groups: dict[tuple[float, int, float, bool, float | None, float], str] = {}
    representative: dict[str, PreferredStock] = {}
    for p in preferred:
        key = (
            p.price,
            p.seniority,
            p.liquidation_multiple,
            p.participating,
            p.participation_cap,
            p.conversion_ratio,
        )
        class_id = groups.setdefault(key, f"ovf-preferred-{len(groups) + 1}")
        class_of[p.security_id] = class_id
        representative.setdefault(class_id, p)

    quantity = {s.security_id: _numeric(s.shares, f"{s.security_id}.shares") for s in equity}
    price = {s.security_id: _numeric(s.price, f"{s.security_id}.price") for s in equity}

    stock_classes: list[StockClass] = []
    if table.securities:
        stock_classes.append(
            StockClass(
                object_type="STOCK_CLASS",
                id=COMMON_CLASS_ID,
                name="Common Stock",
                class_type="COMMON",
                default_id_prefix="CS-",
                initial_shares_authorized=_decimal_sum(
                    [quantity[s.security_id] for s in equity if isinstance(s, CommonStock)]
                ),
                votes_per_share="1",
                seniority="1",
                comments=(_CLASS_NOTE,),
            )
        )
    for number, (class_id, sample) in enumerate(representative.items(), start=1):
        where = f"PreferredStock {sample.security_id!r}"
        multiple = _numeric(sample.liquidation_multiple, f"{where}.liquidation_multiple")
        cap: str | None = None
        if sample.participation_cap is not None:
            cap = _numeric(sample.participation_cap, f"{where}.participation_cap")
            if participation_cap_basis == "participation_only":
                cap = format(Decimal(cap) - Decimal(multiple), "f")
        ratio = _ratio(sample.conversion_ratio)
        stock_classes.append(
            StockClass(
                object_type="STOCK_CLASS",
                id=class_id,
                name=f"Preferred class {number}",
                class_type="PREFERRED",
                default_id_prefix="PS-",
                initial_shares_authorized=_decimal_sum(
                    [
                        quantity[p.security_id]
                        for p in preferred
                        if class_of[p.security_id] == class_id
                    ]
                ),
                votes_per_share="1",
                seniority=ocf_seniority[sample.seniority],
                price_per_share=Monetary(amount=price[sample.security_id], currency=currency),
                conversion_rights=(
                    StockClassConversionRight(
                        type="STOCK_CLASS_CONVERSION_RIGHT",
                        conversion_mechanism=RatioConversionMechanism(
                            type="RATIO_CONVERSION",
                            conversion_price=Monetary(
                                amount=_conversion_price(price[sample.security_id], ratio),
                                currency=currency,
                            ),
                            ratio=ratio,
                            rounding_type="NORMAL",
                        ),
                        converts_to_stock_class_id=COMMON_CLASS_ID,
                    ),
                ),
                liquidation_preference_multiple=multiple,
                participation_cap_multiple=cap,
                comments=(
                    _CLASS_NOTE,
                    "conversion_price is price_per_share / ratio rounded to 10 decimals and "
                    "rounding_type is a placeholder; ovf reads only the ratio.",
                ),
            )
        )

    provided = dict(stakeholders or {})
    holder_ids = list(
        dict.fromkeys([*(s.holder_id for s in equity), *(n.holder_id for n in notes)])
    )
    unknown = sorted(set(provided) - set(holder_ids))
    if unknown:
        raise ValueError(f"stakeholders given for holder_ids not in the table: {unknown}")
    stakeholder_objects: list[Stakeholder] = []
    for holder_id in holder_ids:
        record = provided.get(holder_id)
        if record is None:
            record = Stakeholder(
                object_type="STAKEHOLDER",
                id=holder_id,
                name=Name(legal_name=holder_id),
                stakeholder_type="INSTITUTION",
                comments=(_STAKEHOLDER_NOTE,),
            )
        elif record.id != holder_id:
            raise ValueError(
                f"stakeholders[{holder_id!r}].id is {record.id!r}; it must equal the holder_id"
            )
        stakeholder_objects.append(record)

    issuances = [
        StockIssuance(
            object_type="TX_STOCK_ISSUANCE",
            id=f"ovf-issuance-{s.security_id}",
            date=as_of,
            security_id=s.security_id,
            custom_id=s.security_id,
            stakeholder_id=s.holder_id,
            security_law_exemptions=(),
            stock_class_id=(
                COMMON_CLASS_ID if isinstance(s, CommonStock) else class_of[s.security_id]
            ),
            share_price=Monetary(amount=price[s.security_id], currency=currency),
            quantity=quantity[s.security_id],
            stock_legend_ids=(),
            comments=(
                (_ISSUANCE_NOTE, _UNKNOWN_BASIS_NOTE)
                if isinstance(s, CommonStock) and s.price == 0
                else (_ISSUANCE_NOTE,)
            ),
        )
        for s in equity
    ]
    plans = [
        StockPlan(
            object_type="STOCK_PLAN",
            id=pool.security_id,
            plan_name=pool.security_id,
            initial_shares_reserved=_numeric(
                pool.reserved_shares, f"{pool.security_id}.reserved_shares"
            ),
            stock_class_ids=(COMMON_CLASS_ID,),
            comments=(_PLAN_NOTE,),
        )
        for pool in pools
    ]
    # OCF convertible seniority has "1 being highest seniority", the same direction as ovf
    # debt seniority, so the dense rank is written as it stands (no inversion).
    note_levels = sorted({n.seniority for n in notes})
    note_seniority = {level: index + 1 for index, level in enumerate(note_levels)}
    note_issuances = [_note_issuance(n, currency, note_seniority[n.seniority]) for n in notes]

    object_ids = [
        *(c.id for c in stock_classes),
        *(s.id for s in stakeholder_objects),
        *(p.id for p in plans),
        *(t.id for t in issuances),
        *(t.id for t in note_issuances),
    ]
    collisions = sorted({i for i in object_ids if object_ids.count(i) > 1})
    if collisions:
        raise OcfUnsupportedError(
            f"OCF object ids would collide: {collisions}. Holder ids, pool security_ids and "
            f"the generated ids '{COMMON_CLASS_ID}', 'ovf-preferred-N' and "
            "'ovf-issuance-<security_id>' share one namespace; rename the colliding ovf ids."
        )

    return OcfPackage(
        ocf_version="1.2.0",
        issuer=issuer,
        as_of=as_of,
        generated_at=generated_at,
        comments=(
            f"{_GENERATED} OCF {OCF_VERSION}; participation_cap_basis="
            f"{participation_cap_basis}. See docs/ocf.md in the ovf repository.",
        ),
        stock_classes=tuple(stock_classes),
        stakeholders=tuple(stakeholder_objects),
        stock_plans=tuple(plans),
        transactions=tuple(
            t.model_dump(mode="json", exclude_none=True) for t in [*issuances, *note_issuances]
        ),
    )


def _json_bytes(payload: object) -> bytes:
    return (json.dumps(payload, indent=2, ensure_ascii=False, allow_nan=False) + "\n").encode()


def write_ocf_package(package: OcfPackage, directory: str | os.PathLike[str]) -> Path:
    """Write ``package`` as OCF JSON files plus a manifest; return the manifest path.

    ``directory`` must not exist or must be empty; nothing is overwritten. Manifest
    checksums are the MD5 of the bytes written. A package loaded with files ovf did not
    read (vesting terms, valuations, ...) is refused, because writing it would drop them.
    """
    if package.unread_files:
        raise OcfUnsupportedError(
            f"This package was loaded with files ovf does not read {list(package.unread_files)}; "
            "writing it would silently drop them."
        )
    target = Path(directory)
    if target.exists() and (not target.is_dir() or any(target.iterdir())):
        raise FileExistsError(f"{target} exists and is not an empty directory")
    target.mkdir(parents=True, exist_ok=True)

    def write(filename: str, file_type: str, items: list[object]) -> tuple[FileReference, ...]:
        data = _json_bytes({"file_type": file_type, "items": items})
        (target / filename).write_bytes(data)
        digest = hashlib.md5(data, usedforsecurity=False).hexdigest()
        return (FileReference(filepath=f"./{filename}", md5=digest),)

    manifest = Manifest(
        file_type="OCF_MANIFEST_FILE",
        ocf_version=package.ocf_version,
        issuer=package.issuer,
        as_of=package.as_of,
        generated_at=package.generated_at,
        comments=package.comments or None,
        stock_classes_files=write(
            "StockClasses.ocf.json",
            "OCF_STOCK_CLASSES_FILE",
            [c.model_dump(mode="json", exclude_none=True) for c in package.stock_classes],
        ),
        stakeholders_files=write(
            "Stakeholders.ocf.json",
            "OCF_STAKEHOLDERS_FILE",
            [s.model_dump(mode="json", exclude_none=True) for s in package.stakeholders],
        ),
        stock_plans_files=write(
            "StockPlans.ocf.json",
            "OCF_STOCK_PLANS_FILE",
            [p.model_dump(mode="json", exclude_none=True) for p in package.stock_plans],
        ),
        transactions_files=write(
            "Transactions.ocf.json", "OCF_TRANSACTIONS_FILE", list(package.transactions)
        ),
        stock_legend_templates_files=(),
        vesting_terms_files=(),
        valuations_files=(),
    )
    manifest_path = target / "Manifest.ocf.json"
    manifest_path.write_bytes(_json_bytes(manifest.model_dump(mode="json", exclude_none=True)))
    return manifest_path
